"use client";

import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card } from "@/components/ui/card";
import { useAnalytics } from "@/hooks/use-quiz";

const performance = [{ name: "Mon", score: 72 }, { name: "Tue", score: 78 }, { name: "Wed", score: 81 }, { name: "Thu", score: 86 }, { name: "Fri", score: 91 }];
const difficulty = [{ name: "Easy", value: 28 }, { name: "Medium", value: 52 }, { name: "Hard", value: 20 }];
const bloom = [{ name: "Remember", value: 12 }, { name: "Understand", value: 18 }, { name: "Apply", value: 20 }, { name: "Analyze", value: 22 }, { name: "Evaluate", value: 16 }, { name: "Create", value: 12 }];
const history = [{ topic: "PostgreSQL", difficulty: "Medium", score: "86%" }, { topic: "Redis", difficulty: "Easy", score: "92%" }, { topic: "Vector DBs", difficulty: "Hard", score: "78%" }];
const colors = ["#8b5cf6", "#06b6d4", "#22c55e", "#f59e0b", "#ef4444", "#ec4899"];

export default function AnalyticsPage() {
  const { data, isLoading, isError } = useAnalytics();
  return <main className="mx-auto max-w-7xl px-6 py-10"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-primary">Analytics Dashboard</p><h1 className="mt-2 text-4xl font-black">Assessment intelligence</h1>{isError ? <p className="mt-2 text-red-300">Live backend analytics unavailable; showing dashboard sample data.</p> : null}</div><div className="grid gap-5 md:grid-cols-3"><Card><p className="text-muted-foreground">Quiz History</p><p className="text-4xl font-black">{isLoading ? "..." : data?.quiz_count ?? history.length}</p></Card><Card><p className="text-muted-foreground">Avg Generation</p><p className="text-4xl font-black">{Math.round(data?.average_generation_ms ?? 840)}ms</p></Card><Card><p className="text-muted-foreground">Avg Score</p><p className="text-4xl font-black">84%</p></Card></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Performance Trends</h2><div className="h-72"><ResponsiveContainer><LineChart data={performance}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Line type="monotone" dataKey="score" stroke="#8b5cf6" strokeWidth={3} /></LineChart></ResponsiveContainer></div></Card><Card><h2 className="text-xl font-bold">Difficulty Analysis</h2><div className="h-72"><ResponsiveContainer><BarChart data={difficulty}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#06b6d4" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></Card><Card><h2 className="text-xl font-bold">Bloom Level Distribution</h2><div className="h-72"><ResponsiveContainer><PieChart><Pie data={bloom} dataKey="value" nameKey="name" outerRadius={95} label>{bloom.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></Card><Card><h2 className="text-xl font-bold">Recent Quiz History</h2><div className="mt-4 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/10"><tr><th className="p-3">Topic</th><th className="p-3">Difficulty</th><th className="p-3">Score</th></tr></thead><tbody>{history.map((item) => <tr key={item.topic} className="border-t border-white/10"><td className="p-3">{item.topic}</td><td className="p-3">{item.difficulty}</td><td className="p-3">{item.score}</td></tr>)}</tbody></table></div></Card></div></main>;
}
